stages:
  - cpplint
  - pycodestyle
  - benchmark

cpplint:
  stage: cpplint
  script:
    - curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
    - python cpplint.py --linelength=80 --counting=detailed $(find nnbench -name "*.h" -or -name "*.cc")

pycodestyle:
  stage: pycodestyle
  script:
    - pycodestyle $(find -name "*.py")

benchmark:
  stage: benchmark
  script:
    - DATE_STR=`date "+%Y_%m_%d"`
    - CI_PROJECT_OUTPUT_PATH=/nnbench-build-output/$CI_PROJECT_NAME/${DATE_STR}_${CI_PIPELINE_ID}
    - ANDROID_NDK_HOME=/opt/android-ndk-r15c
    - python tools/benchmark.py --output_dir=$CI_PROJECT_OUTPUT_PATH
    - if [ -f $CI_PROJECT_OUTPUT_PATH/report.csv ]; then cp $CI_PROJECT_OUTPUT_PATH/report.csv .; cat report.csv | sed 's/,/ ,/g' | column -t -s,; fi
  artifacts:
      paths:
        - report.csv

