stages:
  - cpplint
  - pycodestyle
  - benchmark

cpplint:
  stage: cpplint
  script:
    - curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
    - python cpplint.py --linelength=80 --counting=detailed $(find aibench -name "*.h" -or -name "*.cc")

pycodestyle:
  stage: pycodestyle
  script:
    - pycodestyle $(find tools -name "*.py")

benchmark:
  stage: benchmark
  script:
    - DATE_STR=`date "+%Y_%m_%d"`
    - CI_PROJECT_OUTPUT_PATH=/mace-build-output/$CI_PROJECT_NAME/${DATE_STR}_${CI_PIPELINE_ID}
    - mkdir -p $CI_PROJECT_OUTPUT_PATH
    - ANDROID_NDK_HOME=/opt/android-ndk-r15c
    - python tools/benchmark.py --output_dir=$CI_PROJECT_OUTPUT_PATH --target_abis=armeabi-v7a,arm64-v8a
    - >
      cp $CI_PROJECT_OUTPUT_PATH/*_report.csv .;
      echo "------------------------------------------------------------------";
      echo "Run Time Average (See FAQ section in README for more explanations)";
      echo "------------------------------------------------------------------";
      cat run_report.csv | sed 's/,/ ,/g' | column -t -s,;
      echo "------------------------------------------------------------------";
      echo "Prepare Time (see FAQ section in README for more explanations)";
      echo "------------------------------------------------------------------";
      cat prepare_report.csv | sed 's/,/ ,/g' | column -t -s,;
  artifacts:
      paths:
        - prepare_report.csv
        - run_report.csv
