stages:
  - cpplint
  - benchmark

cpplint:
  stage: cpplint
  script:
    - curl -o cpplint.py https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
    - python cpplint.py --linelength=80 --counting=detailed $(find nnbench -name "*.h" -or -name "*.cc")

benchmark:
  stage: benchmark
  script:
    - bazel build //nnbench/benchmark:model_benchmark --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a --copt=-std=c++11 --action_env=ANDROID_NDK_HOME=/opt/android-ndk-r15c
